services:
  app:
    build:
      context: .
      args:
        TORCH_EXTRA: cu126
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  app-test:
    build:
      context: .
      args:
        TORCH_EXTRA: cu126
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
