"""removed gemini embedding table, instead added gemini embedding column to Page table

Revision ID: 0d2ae2783bb1
Revises: b6d75f428aab
Create Date: 2026-07-03 21:19:08.137125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = "0d2ae2783bb1"
down_revision: Union[str, Sequence[str], None] = "b6d75f428aab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gemini_page_embedding")
    op.add_column(
        "page",
        sa.Column(
            "gemini_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            nullable=True,
        ),
    )
    op.drop_column("page", "col_embeddings_failed")
    op.drop_column("page", "embedding_failed")
    op.drop_column("page", "image_failed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "page",
        sa.Column(
            "image_failed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "page",
        sa.Column(
            "embedding_failed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "page",
        sa.Column(
            "col_embeddings_failed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("page", "gemini_embedding")
    op.create_table(
        "gemini_page_embedding",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("page_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["page.id"],
            name=op.f("gemini_page_embedding_page_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("gemini_page_embedding_pkey")),
        sa.UniqueConstraint(
            "page_id",
            name=op.f("gemini_page_embedding_page_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
