"""added qwen vl 8b embedding column

Revision ID: 25fbd190e0d8
Revises: 33726cbfb806
Create Date: 2026-07-19 22:33:43.766878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '25fbd190e0d8'
down_revision: Union[str, Sequence[str], None] = '33726cbfb806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('qwen3_8b_embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=3584), nullable=True))
    op.create_index('ix_page_qwen3_8b_embedding_hnsw', 'page', ['qwen3_8b_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'qwen3_8b_embedding': 'halfvec_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_qwen3_8b_embedding_hnsw', table_name='page', postgresql_using='hnsw', postgresql_ops={'qwen3_8b_embedding': 'halfvec_cosine_ops'})
    op.drop_column('page', 'qwen3_8b_embedding')
    # ### end Alembic commands ###
