"""created annotation table

Revision ID: 33726cbfb806
Revises: 0f56af719798
Create Date: 2026-07-19 13:22:12.730607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33726cbfb806'
down_revision: Union[str, Sequence[str], None] = '0f56af719798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotator', sa.String(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotator', 'query_id', 'page_id', name='uq_annotation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_annotation')
    # ### end Alembic commands ###
