"""added text column to page

Revision ID: 3581b589e4c9
Revises: 048cd3e27769
Create Date: 2026-07-20 01:17:56.622781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3581b589e4c9'
down_revision: Union[str, Sequence[str], None] = '048cd3e27769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('text', sa.String(), nullable=True))
    op.add_column('page', sa.Column('text_failed', sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'text_failed')
    op.drop_column('page', 'text')
    # ### end Alembic commands ###
