"""update uq_annotation to use annotator_id

Revision ID: 40e58058be64
Revises: 97a1cbfebeae
Create Date: 2026-10-04 01:57:37.971433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e58058be64'
down_revision: Union[str, Sequence[str], None] = '97a1cbfebeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_annotation'), 'evaluation_annotation', type_='unique')
    op.create_unique_constraint('uq_annotation', 'evaluation_annotation', ['annotator_id', 'query_id', 'page_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_annotation', 'evaluation_annotation', type_='unique')
    op.create_unique_constraint(op.f('uq_annotation'), 'evaluation_annotation', ['annotator', 'query_id', 'page_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
