"""Changed indexes to unique constraints for path and image_path

Revision ID: 55fb2444f297
Revises: d1d4fefd4883
Create Date: 2026-07-17 17:25:05.386965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fb2444f297'
down_revision: Union[str, Sequence[str], None] = 'd1d4fefd4883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_path'), table_name='document')
    op.create_unique_constraint(None, 'document', ['path'])
    op.drop_index(op.f('ix_page_image_path'), table_name='page')
    op.create_unique_constraint(None, 'page', ['image_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page', type_='unique')
    op.create_index(op.f('ix_page_image_path'), 'page', ['image_path'], unique=False)
    op.drop_constraint(None, 'document', type_='unique')
    op.create_index(op.f('ix_document_path'), 'document', ['path'], unique=False)
    # ### end Alembic commands ###
