"""added columns to nstx tables

Revision ID: cd848ddd7cea
Revises: f8597f27dbab
Create Date: 2026-07-08 15:53:16.133551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd848ddd7cea'
down_revision: Union[str, Sequence[str], None] = 'f8597f27dbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nstx_embeddings', sa.Column('figure_id', sa.String(), nullable=True))
    op.add_column('nstx_papers', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('nstx_papers', sa.Column('page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nstx_papers', 'page_count')
    op.drop_column('nstx_papers', 'document_type')
    op.drop_column('nstx_embeddings', 'figure_id')
    # ### end Alembic commands ###
