"""added annotator table

Revision ID: cf03e2bf30d5
Revises: 6e400c1df9fa
Create Date: 2026-10-03 23:11:47.893806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf03e2bf30d5'
down_revision: Union[str, Sequence[str], None] = '6e400c1df9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotator_name'), 'annotator', ['name'], unique=True)
    # ### end Alembic commands ###
    
    op.execute("""
        INSERT INTO annotator (name, role)
        SELECT DISTINCT annotator, 
        CASE
            WHEN annotator IN ('anthropic:claude-fable-5-1','gemini-3.1-pro','gemini-3.8-flash','anthropic:claude-opus-5','gpt-6-astra') THEN 'ai'
            ELSE 'human'
        END AS annotator_role
        FROM evaluation_annotation
        WHERE annotator IS NOT NULL
        ON CONFLICT (name) DO NOTHING
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotator_name'), table_name='annotator')
    op.drop_table('annotator')
    # ### end Alembic commands ###
