"""Added indexes to path and image_path

Revision ID: d1d4fefd4883
Revises: 0d2ae2783bb1
Create Date: 2026-07-17 17:02:46.141876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d4fefd4883'
down_revision: Union[str, Sequence[str], None] = '0d2ae2783bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_path'), 'document', ['path'], unique=False)
    op.create_index(op.f('ix_page_image_path'), 'page', ['image_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_image_path'), table_name='page')
    op.drop_index(op.f('ix_document_path'), table_name='document')
    # ### end Alembic commands ###
