"""created nstx_embeddings and nstx_papers table

Revision ID: f8597f27dbab
Revises: 0d2ae2783bb1
Create Date: 2026-07-08 15:26:48.234132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = 'f8597f27dbab'
down_revision: Union[str, Sequence[str], None] = '0d2ae2783bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nstx_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drive_file_id', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('subfolder', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('publication_date', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('key_findings', sa.String(), nullable=True),
    sa.Column('experiment_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nstx_papers_doi'), 'nstx_papers', ['doi'], unique=False)
    op.create_index(op.f('ix_nstx_papers_drive_file_id'), 'nstx_papers', ['drive_file_id'], unique=True)
    op.create_index(op.f('ix_nstx_papers_id'), 'nstx_papers', ['id'], unique=False)
    op.create_table('nstx_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('image_uri', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['nstx_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nstx_embeddings')
    op.drop_index(op.f('ix_nstx_papers_id'), table_name='nstx_papers')
    op.drop_index(op.f('ix_nstx_papers_drive_file_id'), table_name='nstx_papers')
    op.drop_index(op.f('ix_nstx_papers_doi'), table_name='nstx_papers')
    op.drop_table('nstx_papers')
    # ### end Alembic commands ###
